apiVersion: v1
kind: Service
metadata:
  name: pro-api-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: api-pod
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels.:
    app: api-deployment
  name: pro-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-pod
  template:
    metadata:
      labels.:
        app: api-pod
      name: api-python
    spec:
      containers:
      - image: ingeeduar/ajpython:1.0.1-22
        name: api-container
