apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: pro-
namespace: pro

resources:
  - ../../bases

secretGenerator:
  - name: s-nginx-ssl
    type: "kubernetes.io/tls"
    files:
      - secrets/tls.crt
      - secrets/tls.key

configMapGenerator:
  - name: cm-nginx-server
    files:
      - config/nginx.conf