apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels.:
    app: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-pod
  template:
    metadata:
      name: api-python
      labels:
        app: api-pod
    spec:
      containers:
        - image: ingeeduar/ajpython:1.0.1-23
          name: api-container